apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend-pods
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: punnyoz/backend:latest
          # imagePullPolicy: Never
          env:
            - name: REDIS_HOSTNAME
              value: "redis"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: ALLOWED_HOSTS # HOST URL ex. 34.101.61.75
              value: "*"
            - name: CORS_ALLOWED_ORIGINS # Frontend URL ex. http://localhost:3000
              value: "http://localhost:3000 http://127.0.0.1:3000 http://34.128.108.186 http://34.126.175.208"
          command: ['python', 'manage.py', 'runserver', '0.0.0.0:5000']
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000