# Generated by Django 3.2.9 on 2021-11-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('image_quota', models.IntegerField(default=10)),
                ('video_quota', models.IntegerField(default=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
