# Generated by Django 3.2.9 on 2022-02-15 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211129_0325'),
    ]

    operations = [
        migrations.RunSQL('''SET GLOBAL event_scheduler=ON'''),
        migrations.RunSQL(
            '''CREATE EVENT `ResetQuota`
    ON SCHEDULE EVERY '1' DAY STARTS '2018-02-08T00:00:00+07:00'
    DO
        BEGIN
            update deepgi.users_user set image_quota=10;
            update deepgi.users_user set video_quota=30;
        end;
            '''
        )
    ]
